openapi: 3.0.3
info:
  title: My Shopping Mall (수동 작성 예시용)
  version: 1.0.0
paths:
  /products:
    get:
      summary: 상품 목록 조회
      responses:
        '200' :
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string